# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 罗布斯
subtitle: '生活无捷径，每步皆机会。'
description: '永远不要相信苦难是值得的，苦难就是苦难，它不会带来成功，也不值得追求，磨炼意志是因为苦难无法逃避。'
keywords: 'blog,博客,知识,文章,技术,AI,人工智能,chatgpt,gpt'
author: 罗布斯
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.funning.top/
#permalink: :year/:month/:day/:title/
permalink: article/:abbrlink.html # post为自定义前缀
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

abbrlink:
  alg: crc32   #算法： crc16(default) and crc32
  rep: hex     #进制： dec(default) and hex


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'robots.txt'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: anzhiyu

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/1137882300/1137882300.github.io
  branch: master

  # repo: https://github.com/1137882300/1137882300.github.io
  # repo: https://1137882300:${DEPLOY_TOKEN}@github.com/1137882300/1137882300.github.io.git


# deploy:
#   type: git
#   repo: ${GITHUB_REPOSITORY_URL}
#   branch: master

# deploy:
#   type: git
#   repo: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/1137882300/1137882300.github.io
#   branch: master


# hexo-admin authentification 
admin:
  username: juzi
  password_hash: $2a$10$1XkI1TA8/4V4stg32pHDA.HD6zW/zsuhIO8ViQUrEg5oizxdIc/RC
  secret: xiaopangxie

# 搜索相关的 https://dashboard.algolia.com/account/api-keys/restricted?applicationId=8Y3BT0M4D5
algolia:
  appId: "8Y3BT0M4D5"
  apiKey: "00e7d3d6a2840feeb77ac9e3178f6e6b"
  adminApiKey: "4d3e57496c6c441a8ab6f3aba3f44964"
  chunkSize: 5000
  indexName: "prod_NAME"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

# google收录试用的
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml


# 百度主动推送
baidu_url_submit:
  count: 100 	# 提交最新的一个链接
  host: funning.top # 在百度站长平台中注册的域名
  token: YourToken # 请注意这是你百度站长平台主动推送的的秘钥, 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址, 新链接会保存在此文本文档里

# Baidu Push (百度推送)
baidu_push: true


# Security
encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  tags:
    - {name: 旅游, password: pmt520}
  theme: xray
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# 追番设置
bangumi:
  enable: true
  source: bili
  bgmInfoSource: 'bgmApi'
  path:
  vmid: 365790176
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  lazyload: false
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  showMyComment: false
  pagination: false
  metaColor:
  color:
  webp:
  progress:
  extraOrder:
  order: latest
  proxy:
    host: '代理host'
    port: '代理端口'
  extra_options:
    key: value
cinema: # 追剧设置
  enable: true
  path:
  vmid: 65377793
  title: '追剧列表'
  quote: '生命不息，追剧不止！'
  show: 1
  lazyload: true
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  metaColor:
  color:
  webp:
  progress:
  extraOrder:
  order:
  extra_options:
    key: value

# 豆瓣
douban:
  id: 219406152
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  book:
    path: books/index.html
    title: 'This is my book title'
    quote: 'This is my book quote'
    option:
  movie:
    path: movies/index.html
    title: 'This is my movie title'
    quote: '热爱生活，热爱影视'
    option:
  game:
    path: games/index.html
    title: 'This is my game title'
    quote: 'This is my game quote'
    option:
  song:
    path: songs/index.html
    title: 'This is my song title'
    quote: 'This is my song quote'
    option:
  timeout: 10000